#!/bin/bash

source /usr/share/yunohost/helpers

upstream_source_url=$(ynh_read_manifest "resources.sources.main.url")
index_page=$(basename -s .zip $upstream_source_url).html #this variable will also populate the template tag __INDEX_PAGE__ in nginx.conf

#=================================================
# CHANGE HARDCODED URLS IN APP FILES
#=================================================

# Prepare var for string replacement (empty if $path is root or $path if subdir is defined)
old_path_2=""
if [[ $old_path != '/' ]]; then old_path_2=$old_path; fi
new_path_2=""
if [[ $new_path != '/' ]]; then new_path_2=$new_path; fi

# Replace URL placeholder with $path only in specific cases
index_js_path="$(sed --regexp-extended --silent 's@\s*<script type="module" crossorigin src=".*/(assets/index-[^.]*\.js)\"></script>@\1@p' $install_dir/index.html)" #e.g. assets/index-86994da2.js
sed --regexp-extended --in-place "s@([a-zA-Z0-9^=]*)=\"modulepreload\",([a-zA-Z0-9^=]*)=function\(([a-zA-Z0-9^=]*)\)\{return\"$old_path_2/\"@\1=\"modulepreload\",\2=function\(\3\)\{return\"$new_path_2/\"@g" $install_dir/$index_js_path
sed --regexp-extended --in-place "s@loadEnv\(\{BASE_URL:\"$old_path_2/@loadEnv({BASE_URL:\"$new_path_2/@g" $install_dir/$index_js_path

# Replace base URL recursively in all files of the app folder
match_regex="$old_domain$old_path_2"
grep --extended-regexp --recursive --files-with-matches --ignore-case "$match_regex" $install_dir/* | xargs -d '\n' sed --regexp-extended --in-place "s@$match_regex@$new_domain$new_path_2@g"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Change of URL completed for $app"
