#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="ynh_build"

#Prepare $newpath for string replacement (empty if $path is root or $path if subdir is defined)
newpath=""
if [[ $path != '/' ]]; then newpath=$path; fi

# Replace references to remote Google fonts to local ones
#~ ynh_replace --match="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" --replace="https://$domain$newpath/assets/ynh_localize_fonts.css" --file="$install_dir/index.html"
#~ ynh_replace --match="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" --replace="https://$domain$newpath/assets/ynh_localize_fonts.css" --file="$install_dir/create.html"
#~ sed -i 's@https://fonts\.googleapis\.com/css2?family=Jost&display=swap@https://$domain$newpath/assets/ynh_localize_fonts.css@g' $install_dir/assets/dialog-*.css
#~ ynh_config_add --template="ynh_localize_fonts.css" --destination="$install_dir/assets/ynh_localize_fonts.css"
#~ ynh_config_add --template="material-symbols-outlined-v290-latin-regular.woff2" --destination="$install_dir/assets/material-symbols-outlined-v290-latin-regular.woff2"
#~ ynh_config_add --template="jost-v20-cyrillic_latin_latin-ext-regular.woff2" --destination="$install_dir/assets/jost-v20-cyrillic_latin_latin-ext-regular.woff2"
#~ chown -R "$app:www-data" "$install_dir"

# Replace URL placeholder with absolute URL for all files of the app folder
match_regex="/?__YNH_SUBDIR_PATH__"
grep --extended-regexp --recursive --files-with-matches --ignore-case "$match_regex" $install_dir/* | xargs -d '\n' sed --regexp-extended --in-place "s@$match_regex@$newpath@g"

# Other specific $domain$path replacement
#~ ynh_replace --match="=\"\./" --replace="=\"https://$domain$newpath/" --file="$install_dir/index.html"
#~ ynh_replace --match="\"/create" --replace="=\"https://$domain$newpath/create" --file="$install_dir/index.html"
#~ ynh_replace --match="'../models" --replace="=\"https://$domain$newpath/models" --file="$install_dir/*"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app ..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
