#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="ynh_build"

#Prepare $newpath for string replacement (empty if $path is root or $path if subdir is defined)
newpath=""
if [[ $path != '/' ]]; then newpath=$path; fi

# Replace URL placeholder with $path only in specific cases
#~ index_js_path="$(sed --regexp-extended --silent 's@\s*<script type="module" crossorigin src=".*/(assets/index-[^.]*\.js)\"></script>@\1@p' $install_dir/index.html)" #e.g. assets/index-86994da2.js
#~ sed --regexp-extended --in-place "s@([a-zA-Z0-9^=]*)=\"modulepreload\",([a-zA-Z0-9^=]*)=function\(([a-zA-Z0-9^=]*)\)\{return\"/__YNH_DOMAIN____YNH_SUBDIR_PATH__/\"@\1=\"modulepreload\",\2=function\(\3\)\{return\"$newpath/\"@g" $install_dir/$index_js_path
#~ sed --regexp-extended --in-place "s@loadEnv\(\{BASE_URL:\"/__YNH_DOMAIN____YNH_SUBDIR_PATH__@loadEnv({BASE_URL:\"$path/@g" $install_dir/$index_js_path

# Replace URL placeholder with absolute URL for all files of the app folder
#~ match_regex="/?__YNH_DOMAIN____YNH_SUBDIR_PATH__"
#~ sed --regexp-extended --in-place "s@$match_regex@https://$domain$newpath/@g" $install_dir/manifest.webmanifest
#~ grep --extended-regexp --recursive --files-with-matches --ignore-case "$match_regex" $install_dir/* | xargs -d '\n' sed --regexp-extended --in-place "s@$match_regex@https://$domain$newpath@g"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app ..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
