#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."
	
ynh_setup_source --dest_dir="$install_dir" --source_id="ynh_build" --full_replace=1 --keep="tools-filter.json home.custom.md"

#Prepare $newpath for string replacement (empty if $path is root or $path if subdir is defined)
newpath=""
if [[ $path != '/' ]]; then newpath=$path; fi

# Replace URL placeholder with $path only in specific cases
index_js_path="$(sed --regexp-extended --silent 's@\s*<script type="module" crossorigin src=".*/(assets/index-[^.]*\.js)\"></script>@\1@p' $install_dir/index.html)" #e.g. assets/index-86994da2.js
sed --regexp-extended --in-place "s@([a-zA-Z0-9^=]*)=\"modulepreload\",([a-zA-Z0-9^=]*)=function\(([a-zA-Z0-9^=]*)\)\{return\"/__YNH_DOMAIN____YNH_SUBDIR_PATH__/\"@\1=\"modulepreload\",\2=function\(\3\)\{return\"$newpath/\"@g" $install_dir/$index_js_path
sed --regexp-extended --in-place "s@loadEnv\(\{BASE_URL:\"/__YNH_DOMAIN____YNH_SUBDIR_PATH__@loadEnv({BASE_URL:\"$path/@g" $install_dir/$index_js_path

# Various specific path fixes
sed --regexp-extended --in-place "s@([^,=]*)=\"/__YNH_DOMAIN____YNH_SUBDIR_PATH__\";([^.]*)\.defaults\(\{fontPath:\`\\$\{([^}]*)\}figlet-fonts@\1=\"https://$domain$newpath/\";\2.defaults({fontPath:\`\\$\{\1\}figlet-fonts@g" $install_dir/assets/ascii-text-drawer-*.js
grep --extended-regexp --recursive --files-with-matches --ignore-case "/age_wasm/wasm_exec.js" | xargs -d '\n' sed --regexp-extended --in-place "s@\"/age_wasm/wasm_exec.js@\"/$newpath/age_wasm_wasm_exec.js}/@g"
ynh_replace --match="tools-filter.json" --replace="/tools-filter.json" --file="$install_dir/$index_js_path"
ynh_replace --match="tools-settings.json" --replace="/tools-settings.json" --file="$install_dir/$index_js_path"
ynh_replace --match="home.custom.md" --replace="/home.custom.md" --file="$install_dir/$index_js_path"
ynh_replace --match="https://sharevb-it-tools.vercel.app" --replace="https://$domain$path" --file="$install_dir/index.html"

# Replace URL placeholder with absolute URL for all files of the app folder
match_regex="/?__YNH_DOMAIN____YNH_SUBDIR_PATH__"
sed --regexp-extended --in-place "s@$match_regex@https://$domain$newpath/@g" $install_dir/manifest.webmanifest
grep --extended-regexp --recursive --files-with-matches --ignore-case "$match_regex" $install_dir/* | xargs -d '\n' sed --regexp-extended --in-place "s@$match_regex@https://$domain$newpath@g"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
